export const ADD_TODO = "ADD_TODO";
export const TOGOLLE_TODO = "TOGOLLE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const MARK_COMPLETED = "MARK_COMPLETED";
export const MARK_INCOMPLETE = "MARK_INCOMPLETE";
export const FILTER_TODO = "FILTER_TODO";
export const MARK_ALL_COMPLETE = "MARK_ALL_COMPLETE";
export const UPDATE_SEARCH_TODO = "UPDATE_SEARCH_TODO";
